version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ktor-sample-db
    environment:
      POSTGRES_DB: ktor_sample
      POSTGRES_USER: ktor_user
      POSTGRES_PASSWORD: ktor_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: