### Test Hello World endpoint
GET http://localhost:8080/

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body === "Hello, World!", "Response body doesn't match expected");
    });
%}