ktor:
    application:
        modules:
            - org.jetbrains.ktor.sample.ApplicationKt.module
    deployment:
        port: 8080
jwt:
    issuer: "https://jwt-provider-domain/"
    audience: "jwt-audience"
    realm: "ktor sample app"
    secret: "secret"
database:
    driverClassName: "org.postgresql.Driver"
    host: "localhost"
    port: 5432
    name: "ktor_sample"
    username: "ktor_user"
    password: "ktor_password"
    maxPoolSize: 20
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
flyway:
    locations: "classpath:db/migration"
    baselineOnMigrate: true
ai:
    baseUrl: "http://localhost:8080"
    apiKey: "not-needed-for-local-llama"
    model: "Qwen_QwQ-32B-Q4_K_M.gguf"
