ktor:
    application:
        modules:
            - org.jetbrains.ktor.sample.ApplicationKt.module
    deployment:
        port: 8080
jwt:
    issuer: "https://jwt-provider-domain/"
    audience: "jwt-audience"
    realm: "ktor sample app"
    secret: "secret"
database:
    driverClassName: "org.postgresql.Driver"
    jdbcUrl: "jdbc:postgresql://localhost:5432/ktor_sample"
    username: "ktor_user"
    password: "ktor_password"
    maxPoolSize: 3
