services:
  postgres:
    image: postgres:16-alpine
    container_name: ktor-sample-db
    environment:
      POSTGRES_DB: ktor_sample
      POSTGRES_USER: ktor_user
      POSTGRES_PASSWORD: ktor_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:latest
    container_name: ktor-sample-prometheus
    ports:
      - "9090:9090"
      - "8081:8081"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    container_name: ktor-sample-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTP_PORT=8080
      - KC_HOSTNAME_URL=http://localhost/auth
      - KC_HOSTNAME_ADMIN_URL=http://localhost/auth
      - KC_HOSTNAME_STRICT_BACKCHANNEL=true
      - KC_HTTP_RELATIVE_PATH=/auth
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak_realm.json:/opt/keycloak/data/import/realm.json
    command:
      - start-dev
      - --import-realm

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
