ktor:
  application:
    modules:
      - org.jetbrains.ktor.sample.ApplicationKt.module
  deployment:
    port: "$PORT:8000"
config:
  database:
    driverClassName: "$DB_DRIVER_CLASS_NAME:org.postgresql.Driver"
    host: "$DB_HOST:localhost"
    port: "$DATABASE_PORT:5432"
    name: "$DB_NAME:ktor_sample"
    username: "$DB_USERNAME:ktor_user"
    password: "$DB_PASSWORD:ktor_password"
    maxPoolSize: "$DB_MAX_POOL_SIZE:20"
    cachePrepStmts: "$DB_CACHE_PREP_STMTS:true"
    prepStmtCacheSize: "$DB_PREP_STMT_CACHE_SIZE:250"
    prepStmtCacheSqlLimit: "$DB_PREP_STMT_CACHE_SQL_LIMIT:2048"
  flyway:
    locations: "$FLYWAY_LOCATIONS:classpath:db/migration"
    baselineOnMigrate: "$FLYWAY_BASELINE_ON_MIGRATE:true"
  ai:
    baseUrl: "$AI_BASE_URL:http://localhost:11434"
    apiKey: "$AI_API_KEY:not-needed-for-local-llama"
    model: "$AI_MODEL:gpt-4o-mini"
    tokenizer: "$AI_TOKENIZER:all-minilm-l6-v2-q-tokenizer.json"
    maxSegmentSizeInTokens: "$AI_MAX_SEGMENT_SIZE:550"
    maxOverlapSizeInTokens: "$AI_MAX_OVERLAP_SIZE:50"
  auth:
    authorizeUrl: "$AUTH_URL:https://accounts.google.com/o/oauth2/auth"
    accessTokenUrl: "$AUTH_TOKEN_URL:https://oauth2.googleapis.com/token"
    clientId: "$AUTH_CLIENT_ID:ktor-app"
    clientSecret: "$AUTH_CLIENT_SECRET:<empty>"
    redirectUrl: "$AUTH_REDIRECT_URL:http://localhost/callback"
    encryptionKey: b324d8a737c6cb016f2c1b6e3501ecb2
    signKey: 59aa1b97d4baf65e1a95101aa35cff307fb9c9e653918f14e33736c2bd3362ca
